name: Build Dozy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ldid
        run: brew install ldid

      - name: Build dylib
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Fakesign
        run: ldid -S build/MRvEKUplink.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MRvEKUplink-dylib
          path: build/MRvEKUplink.dylib
